### ISSUE TITLE
Uncaught TypeError: Cannot set property 'twin' of null

### ISSUE THREAD

**Issue by georgegu1997** [Kcnarf/d3-voronoi-map#5]
Hi, I am using this library to draw Voronoi map and meet a weird bug keep reporting:

![bug](https://user-images.githubusercontent.com/18830966/52914304-bc617c00-3301-11e9-8f85-3bfe0fb6c2cc.png)

The error keeps popping out and flushed the console. And sometimes the script stops at the following breakpoint:

```
console.log('at least 1 site has no area, which is not supposed to arise');debugger;
```

I have paid lots of efforts to filter out other possible origins of the bug and please see a minimal example for the bug as follows. Please note that this bug seems to be present at random, and you may need to refresh the browser multiple times to see the complaints. 

```
<!DOCTYPE html>
<html>

<head>
    <script src="http://d3js.org/d3.v5.min.js"></script>
    <script src="https://rawcdn.githack.com/Kcnarf/d3-weighted-voronoi/v1.0.0/build/d3-weighted-voronoi.js"></script>
    <script src="https://rawcdn.githack.com/Kcnarf/d3-voronoi-map/v2.0.0/build/d3-voronoi-map.js"></script>
    <style>
        #glyphDiv {
            height: 800px;
            width: 1000px;
            overflow: scroll;
        }
    </style>
</head>

<body>
    <div id='glyphDiv'>
    </div>
</body>

<script type="text/javascript">
  var data = [
    {size: 0.1},
    {size: 0.2},
    {size: 0.3},
    {size: 0.4},
  ]
  var simu_list = [];
  function test () {
    var simulation = d3.voronoiMapSimulation(data)
      .clip([[-6,10],[-12,0],[-62,0],[-31,54]])
      .weight(function(d) {return d.size})
    simu_list.push(simulation);
  }

  for(var i = 0; i < 100; i ++) {
    test();
  }

</script>

</html>

```

Could anyone help me out?

**Comment by Kcnarf** [comment]
Hi @georgegu1997 

many thanks for your effort on providing this minimal example.

I guess there is 2 issues here:
- one lead to the "cannot set property 'twin' of null"
- one lead to the "at least 1 site has no area, which is not supposed to arise"

Anyway, I will keep you informed on my progress regarding this issue.

**Comment by georgegu1997** [comment]
Thanks for the fast reply! @Kcnarf 

Another information that may be useful: This bug never occurs when the polygon is simpler. For example, if we change the line of polygon input to the following (four borders parallel to the coordinate axes), the bug will not happen.

```
.clip([[0,0],[100,0],[100,100],[0,100]])
```

Thanks again and looking forward to your progress.

**Comment by Kcnarf** [comment]
Always-repeatable, no-need-to-refresh example (with seeded prng), that faces issue _at least 1 site has no area, which is not supposed to arise_ immediatly:

```
<!DOCTYPE html>
<html>
<head>
    <script src="http://d3js.org/d3.v5.min.js"></script>
    <script src="https://rawcdn.githack.com/Kcnarf/d3-weighted-voronoi/v1.0.0/build/d3-weighted-voronoi.js"></script>
    <script src="https://rawcdn.githack.com/Kcnarf/d3-voronoi-map/v2.0.0/build/d3-voronoi-map.js"></script>
</head>

<script type="text/javascript">
var initialSeed = 502;
  var data = [
    {size: .1},
    {size: .2},
    {size: .3},
    {size: .4},
  ]
  var simu_list = [];
  function test (iterationNumber) {
    seed = initialSeed+iterationNumber
    console.log("simulation with seed "+seed);
    var myseededprng = new Math.seedrandom(seed); // (from seedrandom's doc) Use "new" to create a local pprng without altering Math.random
    
    var simulation = d3.voronoiMapSimulation(data)
      .clip([[-6,10],[-12,0],[-62,0],[-31,54]])
      .weight(function(d) {return d.size})
      .prng(myseededprng) 
      .stop();	// immediately stops the simulation; launch each step manualy

      var state = simulation.state();	// retrieve the simulation's state

      while (!state.ended) {
      // manually launch each iteration until the simulation ends
          simulation.tick();
          state = simulation.state();
	}
    
    simu_list.push(simulation);
  }
	
  for(var i = 0; i < 100; i ++) {
    test(i);
  }
</script>
</html>
```

**Comment by Kcnarf** [comment]
debug progress:

- error raised during first step (i.e. during first call of _tick()_)
- because a Voronoï seed is positioned to _Infinity_ (bonus: with random seed = 512, a Voronoï seed is positioned to _NaN_, which raises _cannot set property 'twin' of null_)
- because the very first Voronoï map, computed in _initialization()_ with default weights, returns a map with a near-empty wrongly computed cell:
![capture d ecran 2019-02-19 a 15 46 53](https://user-images.githubusercontent.com/4328986/53023740-14ad9080-345e-11e9-8a52-662ccd9f9902.png)

- found something: the issue seems to not appear when the clipping polygon is entirely in the positive-x and positive-y quadrant ! (i.e., in the very first example, horizontally slide the clipping polygon by 62 to use [[56,10],[50,0],[0,0],[31,54]] instead of [[-6,10],[-12,0],[-62,0],[-31,54]])

**Comment by Kcnarf** [comment]
Use version v1.0.1 of d3-weighted-voronoi (instead of v1.0.0):
````
<script src="https://rawcdn.githack.com/Kcnarf/d3-weighted-voronoi/v1.0.1/build/d3-weighted-voronoi.js"></script>
```

**Comment by georgegu1997** [comment]
Awesome! Thanks for the fast update. Let me try the new version.

BTW, could you please update the npm package so that I can use this library with vue?

**Comment by Kcnarf** [comment]
Yes. d3-weighted-voronoi v1.0.1 is already on npm.

This package depends on `"d3-weighted-voronoi": "1.*"`, so I guess an npm/yarn update/upgrade should retrieve and use the latest 1.0.1 version without any change.

**Comment by eliawk** [comment]
@Kcnarf we are using version 1.1.3 but sometime the script still throw the error: `Cannot set property 'twin' of null
`

**Comment by Kcnarf** [comment]
Hi @eliawk ,
this is embarrassing :-/

Is it possible to provide some context (e.g. a repeatable example, or at least some (anonymized) data that produce the issue) ?

**Comment by eliawk** [comment]
@Kcnarf actually we don't know yet how to replicate the bug, it seems totally random. 
after some interactions with the application the error shows up, but there isn't a specific action that trigger the error.
